---
formatter: markdown table
version: ""
header-from: main.tf
footer-from: ""
recursive:
  enabled: false
  path: " "
sections:
  show:
    - all
content: |-
  [![ReadMeSupportPalestine](https://github.com/Safouene1/support-palestine-banner/blob/master/banner-project.svg)](https://github.com/Safouene1/support-palestine-banner)

  ## Scope
  This is Terraform code to create an Azure Kubernetes service, which enables authorization with Azure Active Directory and auditing for monitor diagnostics.

  ## Usage

  First clone the repository

  ```
  git clone  https://github.com/violenti/aks-terraform-template.git
  cd aks-terraform-template/
  ```

  Edit the file terraform.tfvars with your values and the file backend.tf with "subscription_id", "resource_group_name" of your storage account and name in  "storage_account_name".

  For to initialize the backend, your can do the next command:

  ```
  terraform init -reconfigure -backend-config="key="placeholder.tfstate -backend-config="container_name=placeholder"
  ```

  Run the following command to create it:

  ```
  terraform validate

  terraform plan

  terraform apply
  ```

  ### Installation of pre-commit and terraform docs for Ubuntu 20.04 and higher

  ```
  sudo apt update
  sudo apt install -y unzip software-properties-common python3 python3-pip

  python3 -m pip install --upgrade pip

  pip/pip3 install -r requirements.txt

  curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && tar -xzf terraform-docs.tgz terraform-docs && rm terraform-docs.tgz && chmod +x terraform-docs && sudo mv terraform-docs /usr/bin/
  cd <project_folder_name>/
  pre-commit install
  ```

  ### Installation of pre-commitand terraform docs for MacOS with Brew

  ```
  brew install pre-commit terraform-docs
  ```

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true